# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/main";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."main".device = "/dev/disk/by-uuid/37853260-8ba4-4272-95dd-004589b02adf";

  fileSystems."/home" =
    { device = "/dev/mapper/main";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/main";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/persist" =
    { device = "/dev/mapper/main";
      fsType = "btrfs";
      options = [ "subvol=@persist" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/mapper/main";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/mapper/main";
      fsType = "btrfs";
      options = [ "subvol=@cache" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/mapper/main";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/var/lib/libvirt" =
    { device = "/dev/mapper/main";
      fsType = "btrfs";
      options = [ "subvol=@libvirt" ];
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/mapper/main";
      fsType = "btrfs";
      options = [ "subvol=@docker" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3FD9-2C49";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/db0d8092-634b-4542-8a95-1e6d34bf112f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
